version: '3.7'

x-var: &LOCAL_UID 1000
x-var: &LOCAL_GID 1000

services:
  mail:
    build:
      context: .
      dockerfile: ./containers/mailrelay/Dockerfile
    env_file:
      - ./environments/secret/mailrelay.env
    image: logorg-mailrelay-dev
    ports:
      - '25:25'

  terraform:
    image: hashicorp/terraform:0.14.10
    container_name: terraform
    volumes:
      - ./terraform:/terraform
      - ./environments/secret/terraform.tfvars:/terraform/terraform.tfvars:ro
    env_file: ./environments/secret/terraform.env
    working_dir: ${TERRAFORM_WORK_DIR:-/terraform}

  db:
    image: mysql:8.0
    env_file:
      - ./environments/db.env
      - ./environments/dbroot.env
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dev-mysql-data:/var/lib/mysql

  dbinit:
    build:
      context: .
      dockerfile: ./containers/db-init/Dockerfile
    image: logorg-dbinit-dev
    env_file:
      - ./environments/db.env
      - ./environments/dbroot.env

    depends_on:
      - db

  app:
    environment:
      - LOCAL_UID=1000
      - LOCAL_GID=1000
    env_file:
      - ./environments/db.env
      - ./environments/project.env
    build:
      context: .
      dockerfile: ./containers/logorg/Dockerfile
      args:
        TARGET_ENV: development
    image: logorg-rails-dev
    container_name: logorg_develop
    ports:
      - 3000:3000
      - 9229:9229
  # command: bundle exec rails s -p 3000 -b 0.0.0.0
    command: bundle exec puma -e development -C config/puma.rb
    depends_on:
      - db
      - dbinit
    volumes:
      - .:/project
      - dev-public-data:/project/public
      - dev-tmp-data:/project/tmp
      - dev-log-data:/project/log
    stdin_open: true
    tty: true

  web:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
      args:
        LOCAL_UID: *LOCAL_UID
        LOCAL_GID: *LOCAL_GID
    image: logorg-nginx-dev
    command: /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    volumes:
      - dev-public-data:/project/public
      - dev-tmp-data:/project/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  dev-mysql-data:
    driver: local
  dev-public-data:
    driver_opts:
      type: none
      device: ${PWD}/containers/logorg/dev_tmp/public
      o: bind
  dev-tmp-data:
  dev-log-data:

